title: Sebastian Pazirai # your name (or website title) here
logo: "/images/croppedProfile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

Hi, I am currently in my graduation year to become an engineer in computer science at KTH Royal Institute of Technology.
My work related passions are frontend and backend development. 
I have alot of experience working in groups with agile project methods but I also work just as well individually.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
