title: Sebastian Pazirai # your name (or website title) here
logo: "/images/croppedProfile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br><br>
  Hi! I am currently in my graduation year to become an engineer in computer science
  at KTH Royal Institute of Technology. My work related passions are frontend
  and backend development. I have alot of experience working in groups with 
  agile project methods but I also work great individually.
  <br><br>
  <a href="https://www.linkedin.com/in/sebastian-pazirai-b44b6a198/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
